image:
  repository: ghcr.io/kuberless/apiserver
  tag: latest
  pullPolicy: IfNotPresent
replicas: 2
port: 8080
resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
postgresql:
  existingSecret: kuberless-db
  secretKey: database-url
